---
name: lint

on:
  push:
    branches:
    - pyroscope
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 

      - name: install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      
      - name: ansible lint 
        run: |
          . venv/bin/activate
          ansible-lint -c test/lint/.ansible-lint defaults/*.yml meta/*.yml tasks/*.yml meta/*.yml vars/*.yml
